#!/bin/bash

while [ -z "$ONLINE" ]
do
   ONLINE=$(ping -q -c 1 www.google.com | grep "1 received")
   if [ -z "$ONLINE" ]
     then
       sleep 10
	echo "we are offline!"
   fi
done
echo "We are online!"
