#!/bin/bash

while [ -z "$ONLINE" ]
do
    ONLINEETH=$(ping -q -I eth0 -c 1 8.8.8.8 | grep "1 received")
    if [ -z "$ONLINEETH" ]
    then
   	ONLINEPPP=$(ping -q -I ppp0 -c 1 8.8.8.8 | grep "1 received")
   	if [ -z "$ONLINEPPP" ]
	then
	    echo "we are offline!"
            sleep 30
	else
	    ONLINE=$ONLINEPPP
	    echo "we are online via modem!"
	    break
	fi
    else
	ONLINE=$ONLINEETH
	echo "we are online via ethernet!"
    fi
done
