#!/usr/bin/expect -f

set modem /dev/ttyS0
set timeout 2

exec stty -F $modem 115200 -clocal -echo -istrip -hup

send_user "Connecting to $modem\n"

spawn -open [ open $modem { RDWR NONBLOCK } ]

send "AT\r"
expect {
    "OK" {
	send "AT+IPR=921600\r"
	expect "OK" {
	    exec stty -F $modem 921600 -clocal -echo -istrip -hup
	}
    }
    timeout {
	exec stty -F $modem 921600 -clocal -echo -istrip -hup
    }
}

send "AT#SIMDET=0\r"
expect "OK"
sleep 0.5
send "AT#GPIO=6,1,1\r"
expect "OK"
sleep 0.5
send "AT#SIMDET=1\r"
expect "OK"
sleep 2

set counter 0

while {$counter < 5} {
    incr counter
    send "AT+CPIN?\r"
    expect {
	"+CPIN: READY" {
	    sleep 6
	    send "AT+CREG?\r"
	    expect {
		"+CREG: 0,1" {
		    send "AT&K0\r"
		    expect "OK"
		    send "AT\Q\r"
		    expect "OK"
		    exec echo 1 > /tmp/modemInit
		    exit
		}
		"+CREG: 0,5" {
		    send "AT&K0\r"
		    expect "OK"
		    send "AT\Q\r"
		    expect "OK"
		    exec echo 1 > /tmp/modemInit
		    exit
		}
	    }
	}
	"ERROR" {
	    send "AT#SIMDET=0\r"
	    expect "OK"
	    send "AT#GPIO=6,1,1\r"
	    expect "OK"
	    send "AT#SIMDET=1\r"
	    expect "OK"
	    sleep 2
	}
    }
}

exec echo 0 > /tmp/modemInit

send_user "cdcpinternet connection timeout\r\n"
