#!/bin/sh

if [ -e /dev/ttyS0 ]
then
	if [ ! -e /sys/class/gpio/gpio21 ]
	then
		echo 21 > /sys/class/gpio/export
		sleep 0.5
	fi
	echo out > /sys/class/gpio/gpio21/direction
	sleep 0.5
	echo 1 > /sys/class/gpio/gpio21/value
	sleep 2
	echo 0 > /sys/class/gpio/gpio21/value
	sleep 4
	echo "starting ppp connection"
	if ( ps cax | grep pppd ) > /dev/null
	then
		poff provider
		sleep 1
	fi
	/home/pi/cdcpinternet
else
	echo "No Modem detected."
fi
